language: go

dist: trusty

go:
  - 1.9.x

branches:
  only:
    - master

sudo: false

install:
  - mkdir -p $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  - git clone --branch "v1.0.0" --depth 1 https://github.com/hashicorp/consul.git $GOPATH/src/github.com/hashicorp/consul
  - go install github.com/hashicorp/consul/test/porter/cmd/porter
  - wget "https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64" -O $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - wget "https://releases.hashicorp.com/consul/1.0.0/consul_1.0.0_linux_amd64.zip"
  - unzip -d $HOME/bin consul_1.0.0_linux_amd64.zip
  - $GOPATH/bin/dep ensure -v

before_script:
  - go vet ./

script:
  - $GOPATH/bin/porter go test -v
